### ISSUE TITLE
running AutoQC on AWS

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#105]
Pushing all of *quota* through AutoQC on my home machine takes ~20 hours; it may behoove us to be prepared to run full data reduction runs on AWS. Here are some notes on how I got AutoQC up and running there:

 - make a [free account](http://aws.amazon.com/) at AWS
 - follow the [instructions to set up access to EC2](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/get-set-up-for-amazon-ec2.html) - I followed these exactly, except for the warnings about not allowing ssh from anywhere; there's no security concerns here, easiest to just allow ssh.
 - After signing in as your IAM user from the last step, go to the 'Services' link in the top navigation bar, and choose:
  - EC2
  - launch instance
  - amazon linux
  - t2.micro
  - launch

After launching this compute cluster, a link is presented to go back to the list of instances; go there, wait for this new instance to finish initializing, click on it, click connect at the top, and follow the instructions to ssh into your new node.

Once there, set up AutoQC and all its dependencies via the following:

```
wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.3.0-Linux-x86_64.sh
bash Anaconda-2.3.0-Linux-x86_64.sh
```
(disconnect / reconnect)
```
sudo yum -y install geos
conda install netcdf4
sudo yum -y install git
git clone https://github.com/IQuOD/AutoQC.git
sudo yum -y install gcc-c++ python27-devel atlas-sse3-devel lapack-devel
pip install -r requirements.txt
```

After which AutoQC runs happily on the demo dataset it ships with. Next up will be sticking *quota* on S3, and parallelizing. Should be simple enough to slice *quota* up into pieces and run in parallel - nothing too fancy should be required.

Note this service is not free - the setup demo I described above should (should) run on free-tier resources, but a large cluster to run on all of *quota* will cost a few dollars; hopefully this will be in the single digits and will only have to be run very rarely to reduce the full raw dataset.

**Comment by BillMills** [comment]
Note continued: uploading raw data to S3 is straightforward, but mounting is a bit fraught; the instructions [here](https://github.com/s3fs-fuse/s3fs-fuse) mostly do the job, but I also needed some extra dependencies:
```
sudo yum install gcc libstdc++-devel gcc-c++ fuse fuse-devel curl-devel libxml2-devel openssl-devel mailcap
```

After this and the above, a c3.8xlarge cluster analyzed all of *quota* in about 30 minutes, after using the `splitData.py` script introduced in #107 to divide the dataset into 30 equal parts, analyzing each component in its own process. This compute time corresponds (far as I can tell) to $1.68 in fees.

**Comment by BillMills** [comment]
S3 cont: also useful are [these instructions](http://stackoverflow.com/questions/8659382/downloading-an-entire-s3-bucket) (and also see [these](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration) for authentication) for downloading results en masse off of S3 afterwards.

**Comment by s-good** [comment]
Hi @BillMills, this sounds great! I'm not sure if this is possible, but I was wondering it is possible to supply the list of profiles to the parallel processing rather than a list of files? This would avoid the extra step of splitting the data files. Either way, there is potentially an minor issue with checks that need to know about other profiles (e.g. the track check) as all the required profiles may not be in the same file. I guess, however, this could be avoided by reading in all profile headers to a master list and saving them in the data store before going into the parallel section?

**Comment by BillMills** [comment]
No problem - one of my many to-do's is to wrap this up a little more concisely so it's a bit clearer / easier to reproduce (might even try making a Docker image, we'll see).

Anyway, yes you're exactly right on the issues with the track check, as I mentioned in #93. My intention is to re-do the data file splitting (see `util/splitData.py`) to sort profiles based on what track they are in, since this involves the minimal rewriting of our infrastructure; the only possible problem, is if you foresee many different such sorts needed that are badly disjoint (like needing all profiles on a given track to be in one file, and all profiles that satisfy some other condition to be in one file, and those two conditions are wildly different / uncorrelated such that it's impossible to satisfy both at once without just jamming everything together in one giant file and a single thread).

We could do as you describe, with a master list that then assigns subsets of profiles to individual threads; but that would convolve the data sorting with the data QC, which is just asking for trouble. By splitting our data up optimally in a separate script before we even think about QC, we have two 'simple' things to get right, instead of one complicated thing. One of my biggest concerns for AutoQC right now is its infrastructural complication; unit testing there is a bit patchy, so I am hesitant to complicate things there any further if we can find ways to avoid it.

**Comment by BillMills** [comment]
Once I'm 100% convinced we aren't getting a performance hit from Docker, that'll be our recommended running environment for production runs, and we can close out here.

**Comment by BillMills** [comment]
Alright - #122 is merged including basic running instructions; as I mention in that PR, I want to write down how to mount stuff from S3 -> EC2 -> docker in a wiki page; not very hard once you know how to do it, but worth some notes; once that's done, then we'll *really* be ready to close out here (and I can get back to the CSIRO tests :)

**Comment by BillMills** [comment]
Alright, as promised, here are the final bits of instruction necessary to do a full production run on AWS using Docker: https://github.com/IQuOD/AutoQC/wiki/Working-with-data-on-Amazon-Web-Services

Also note, we now have a wiki - this would be a good place to add detailed instructions or other text (will probably move the notes about machine learning in there, for example).
