### ISSUE TITLE
Wrap CoTeDe tests so that they can be evaluated in AutoQC

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#109]
CoTeDe includes a lot of QC tests that we don't have implemented yet in AutoQC. Wrapper functions will be written that call the CoTeDe tests from inside AutoQC so that they can be evaluated alongside the other tests in AutoQC.

https://github.com/castelao/CoTeDe

**Comment by s-good** [comment]
Pull requests #112 and #120 introduced the functionality.

**Comment by BillMills** [comment]
Thanks, @s-good!
