### ISSUE TITLE
EN_increasing_depth shortcut

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#157]
@s-good, would it make sense to immediately flag all levels in EN_increasing_depth for profiles where every level has depth = 0? This is a practical performance concern, since there are profiles with thousands of levels in them and no depth info; looking at the test as written, I believe that in this case it will construct an NxN matrix, reject the last level, construct an (N-1)x(N-1) matrix.... which gets pretty painful for N O(1000).

**Comment by s-good** [comment]
That would be fine to do as all levels should end up flagged if they are all 0, so no point in running through the full algorithm in this case.
