### ISSUE TITLE
database wrangling

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#174]
I'm beginning to tinker with a proper database to sit behind AutoQC - I'll keep some notes updated in this issue if anyone wants to follow along (also so I don't forget)...

### engineering choices

 - [This article](https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems) seems to suggest that postgres is the better choice for lots of concurrent database interactions, which we will certainly have in a parallelized environment.
 - the current parallelization scheme is a bit obtuse in its use of `map`; a different suggestion could look something like the following, in `AutoQC.py` instead of the calls to `parallel_function`:

```
  ...
  pool = Pool(processes=int(sys.argv[2]))
  parallel_result = []
  def log_result(result):
    parallel_result.append(result)

  for i in range(len(filenames)):
    pool.apply_async(processFile, (filenames[i],), callback = log_result)
  pool.close()
  pool.join()
  ...
```
  while this does the same thing as the present implementation, the combination of the for loop and `apply_async`might be nice when we switch to postgres, since instead of parallelizing over a pre-defined set of files, we can just keep throwing chunks of the database at new parallel processes in the for loop, without loading the whole thing or even having any prior knowledge of how many processes we're going to spawn, like we would need to to form an array to `map` onto.

### postgres notes

On our current docker image, I got postgres installed and running with a database owned by `root` via the following (which does not exactly match any of the tutorials I found, but rather combines a bunch of them...):

```
apt-get update
apt-get install -y postgresql
/etc/init.d/postgresql start
su - postgres
createuser -s root
createdb root
```

to do this from a Dockerfile, the `apt-get`s are the usual, but the context-specific commands that follow need to be chained together:

```
RUN /etc/init.d/postgresql start && su postgres -c 'createuser -s root' && su postgres -c 'createdb root'
```

### postgres via python

`psycopg2` is a popular way to interact with postgres from python, but it needs a dependency installed first (already integrated into the docker image, reflected in the Dockerfile on branch `postgres`):

```
apt-get install -y libpq-dev python-dev
pip install psycopg2
```

That's all that's needed for the example in `postgres/build-db.py` on the `postgres` branch to work properly.

**Comment by BillMills** [comment]
Branch `postgres` has the beginnings of infrastructure for building a postgres database via (more or less) the above examples; last up will be to retrofit profile ingestion to use the db rather than raw text files.

**Comment by castelao** [comment]
@BillMills @s-good , that's fantastic to learn that you're following my advice way back on using PostgreSQL. I think you're in the right path.

You might have an overhead problem with apply_async as in your example above. Take a look on how I use multiprocessing in [CoTeDe](https://github.com/castelao/CoTeDel), if you haven't done already.
