### ISSUE TITLE
dummy wod ascii text

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#181]
So far, we've been mocking profiles for testing with dummy objects that have (some of) the member functions that wodpy objects provide; ideally, we'd like to be able to generate raw wod ascii text instead, for mocking the current database structure. `EN_track` integration tests can't be meaningfully run without this, since that test must sit upstream of a profile query-and-reconstruct step (to find all the other profiles on the same track as the profile in question).

**Comment by s-good** [comment]
It's going to be decent sized job to write a function to generate wod ascii text. It's not very elegant, but for the standard level check I put all the database access into functions and then in the tests those things get overwritten with alternatives that just return the testing data. Would this work for the track check?

**Comment by BillMills** [comment]
That's generally a good strategy - push as much code into testable units as possible, and leave the awkward, untested part as small as possible. That's essentially what's happening in track right now, but I would like to do full integration tests that test every part of the code; that said, I don't think this needs to block our current run - this is likely something for 2.0.

**Comment by BillMills** [comment]
Now that en_track consumes database columns, we won't need this anymore (instead we'll need to mock some database rows, but that's much less onerous).
