### ISSUE TITLE
Docker help

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#185]
Hi @BillMills, I'm having a bit of a struggle getting postgres to work in the docker container. First problem is that when the docker container starts and tries to start the postgres server it says:

`could not access private key file "server.key"`

The answer [here](http://stackoverflow.com/questions/12087683/postgresql-wont-start-server-key-has-group-or-world-access) seems to get round it but I'm confused why this should be a problem if it works for you as it is?

Once I do the above it then gives another error:

`FATAL: could not create shared memory segment: Invalid argument 2016-08-11 21:11:22 UTC DETAIL: Failed system call was shmget(key=5432001, size=41205760, 03600). 2016-08-11 21:11:22 UTC HINT: This error usually means that PostgreSQL's request for a shared memory segment exceeded your kernel's SHMMAX parameter. You can either reduce the request size or reconfigure the kernel with larger SHMMAX. To reduce the request size (currently 41205760 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections. If the request size is already small, it's possible that it is less than your kernel's SHMMIN parameter, in which case raising the request size or reconfiguring SHMMIN is called for.`

I've not managed to get round this. It sounds like if I edit settings in /etc/sysctl.d/30-postgresql-shm.conf it would work but I think I would need to commit this to the docker image and change the settings for everyone. Any advice?

**Comment by BillMills** [comment]
hm - a couple of simple things:

 - I'm using `Docker version 1.9.1, build a34a1d5`, what do you get from `docker --version`?
 - I launch a container with `docker run -v $PWD:/rawdata --rm -i -t iquod/autoqc /bin/bash`
 - The docker image has been updated not that long ago, maybe do a `docker pull iquod/autoqc`

Probably none of these are the problem, but we need to get on the same page to help you best. Let me know!

**Comment by s-good** [comment]
I'm on Docker version 1.12.0, build 8eab29e. I was doing docker run -i -t iquod/autoqc /bin/bash but the extra bits in your command do not make a difference unfortunately. The docker image is the latest. I just also noticed that there is an additional error in the first problem. The full message is

`Starting PostgreSQL 9.1 database server: main[....] Removed stale pid file. The PostgreSQL server failed to start. Please check the log output: 2016-08-11 21:50:20 UTC FATAL: could not access private key file "server.key"`

**Comment by BillMills** [comment]
If, as soon as you launch the Docker container, you do
```
ls -lsh /var/lib/postgresql/9.1/main
```

What do you get for the `server.key` entry? I get

```
0 lrwxrwxrwx  1 root     root       38 Aug  5 17:16 server.key -> /etc/ssl/private/ssl-cert-snakeoil.key
```

It *should* be the same for you, but more things in heaven and earth. The stack link you posted basically recreates these permissions, except for the `postgres` user instead of the `root` user. What if you try the stack solution, but with `root` instead of `postgres` (unless you already tried that)?

**Comment by s-good** [comment]
I get the same line for server.key:

   0 lrwxrwxrwx 1 root     root       38 Aug  5 17:16 server.key -> /etc/ssl/private/ssl-cert-snakeoil.key

It's all a bit of mystery... I was trying to find work arounds and came across this: https://hub.docker.com/_/postgres/. I managed to download the postgres docker image and ran it using the command given on the page, which is promising, but I'm not sure how to get autoqc working with it.

**Comment by BillMills** [comment]
It might be possible (and advisable) to actually rebuild our docker image using the Postgres image as the base layer; I'll take a swing at that Saturday unless you beat me to it.

**Comment by BillMills** [comment]
Though, before we jump down what might be quite the rabbithole, @s-good can you do a `docker pull billmills/pg-test` and use that image instead of `iquod/autoqc`? It's exactly the same, except it turns off SSL, which we don't need and which is what (I think according to [this](https://www.postgresql.org/message-id/4cba5adc0807020643i2ac04808v5f250c2a790ecdff%40mail.gmail.com)) is making us go fretting over `server.key`. Still weird, but I'll take it at least for now if it gets us to 1.0 on time.

**Comment by s-good** [comment]
The billmills/pg-test image solves the server.key problem but I'm still getting the memory problem. I've managed to find away around that by editing /etc/postgresql/9.1/main/postgreql.conf and setting shared_buffers to 25MB (instead of 32MB). 

What do you see when you do cat /proc/sys/kernel/shmmax? I get 33554432.

Possible solutions seem to be to either increase shmmax (has to be set in the docker image) or reduce the postgres memory settings (can be either set in the docker image or manually edited after starting the container). Not sure which, if either, is the best, though.

**Comment by BillMills** [comment]
```
root@3b3bb9c7b743:/# cat /proc/sys/kernel/shmmax
18446744073692774399
```

What kind of machine are you using at home for this? Is it a linux box? [This comment](https://github.com/docker/docker/issues/10176#issuecomment-75065950) indicates that shmmax gets pulled from the host machine; I'm doing this on my mac and therefore from boot2docker, which sets the huge shmmax above, but a native linux box might have something much smaller.

Docker orthodoxy says to always build images in such a way as to not have to do extra setup steps when you launch a container; `billmills/pg-test` now sets shmmax explicitly in the Dockerfile - give that a go and see if it works (and if you get the same shmmax as me)?

**Comment by s-good** [comment]
Yes, I'm on a linux box. I get the same shmmax with the new image and the shmmax on my linux host is identical to the one in the container so it must be pulling from that. So I could either increase shmmax on my machine (leaves the possibility that others may get the same failure but this is probably not something we need to worry about at the moment) or we could set the postgres shared_buffer setting lower for everyone (might impact performance?).

**Comment by BillMills** [comment]
[Looks like](https://github.com/docker/docker/pull/19265) this was driving other people nuts too, and a flag landed in 1.12. If you launch with:

```
docker run --sysctl "kernel.shmmax=18446744073692774399" -v $PWD:/rawdata --rm -i -t iquod/autoqc /bin/bash
```

Does `cat /proc/sys/kernel/shmmax` give you something bigger?

**Comment by s-good** [comment]
That's done it! Fantastic! Thanks for your help with this.

**Comment by BillMills** [comment]
Great; I guess this one relies on understanding that docker containers all share a common kernel- divided by namespaces, but common still. Anyway, I'll put that launch command in the docs before we merge 'postgres'.
