### ISSUE TITLE
standard level unit test bug?

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#194]
HI @s-good,

I've been picking through the `EN` suite over on `no-global` lately, and I noticed that [this line](https://github.com/IQuOD/AutoQC/blob/master/tests/EN_std_level_background_check_validation.py#L50) in the unit tests looks off; the unit test claims to be looking for a temperature excursion, which it creates in the fake profile a few lines above, but the line linked here shows no flags for any level in the profile, which seems wrong (shouldn't the last one be flagged as a temperature excursion) - which is especially disturbing since the unit test passes! Either there's something more subtle than I currently appreciate happening here, or there's something wrong with this unit test which could possibly be masking a pathology with the qc test itself.

**Comment by s-good** [comment]
This looks like it reproduces a test that is run for the EN background check. When run on reported levels one of the levels gets rejected, but on standard levels it doesn't. Possibly it is not the most useful example, but there are some other tests further down where tests are run on real profiles which are more useful.

**Comment by BillMills** [comment]
Ah, so the standard level test isn't actually supposed to catch that temperature excursion - ok, that makes sense then!
