### ISSUE TITLE
Possible issue with parallel running

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#207]
I think the line below may delete the database table containing the EN background check, so if running in parallel one of the processes could delete information already stored by another.

https://github.com/IQuOD/AutoQC/blob/0ef7ff9b659ffb5e5d11f726756185c80ebe4f15/qctests/EN_background_check.py#L201

**Comment by BillMills** [comment]
You're right, that does delete the db table in question - but doesn't the `loadParameters` function only ever get called before we create the pool of worker processes? That was always the intention, but if this is causing problems then it must be sneaking in somewhere else...

**Comment by s-good** [comment]
Yes, you are right. I'll close the issue.
