### ISSUE TITLE
Result processing

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#22]
Now that useful pass / fail statistics are being generated by the testing pipeline, we can start building summary statistics.  In our previous conversations, @s-good described a summary table that compares test results to an expectation for each dataset, one row in which could be generated by the following:

Given the vector of pass / fail information generated for a test by the testing suite, and a list of the same length and format containing the expected pass / fail performance, write a function that returns a 4-element list that counts, in order,
 - number of datasets that passed when they were expected to pass
 - number of datasets that failed when they were expected to fail
 - number of datasets that passed when they were expected to fail
 - number of datasets that failed when they were expected to pass

**Comment by BillMills** [comment]
does #39 sufficiently address this? Close if so.

**Comment by s-good** [comment]
Yes, #39 sufficiently addresses this so this issue can be closed.
