### ISSUE TITLE
Code up Argo spike test

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#25]
As part of an intercomparison of 'spike tests' (#21) code up the spike test described at http://w3.jcommops.org/FTPRoot/Argo/Doc/argo-quality-control-manual.pdf on page 8. Where this refers to pressure in db, this can be read as depth in m. The program file should be called Argo_spike_test.py and be put into the qctests directory. It should follow the structure shown in EN_range_check.py.

**Comment by BillMills** [comment]
There appear to be two spike tests defined in the reference; the same calculation applied to temperature and salinity. Shall we keep these separate (`Argo_spike_test_temp.py` and `Argo_spike_test_sal.py`), or shall we combine the two spike checks at each depth? The reference has a prescription about what they do when one or both measures show a spike, but how that translates here isn't instantly obvious.

**Comment by s-good** [comment]
For simplicity I suggest we focus on the temperature tests at the moment and ignore salinity so the file can just be named Argo_spike_test.py. We may want to revisit this in the future but I'm not sure at the moment whether it is best to have them separate or in the same file, so I think it best to leave that decision to later.

**Comment by s-good** [comment]
#40 has implemented this test.
