### ISSUE TITLE
Min/max test

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#255]
A new automatic quality control check has been devised called the min/max test. This ticket is to record progress towards implementing it in AutoQC.

**Comment by s-good** [comment]
Test was added: https://github.com/IQuOD/AutoQC/blob/master/qctests/minmax.py.

**Comment by BillMills** [comment]
This test requires some parameter files `data/TEMP_MIN_MAX.nc`, `data/GRID_MIN_MAX.nc` and `data/info_DGG4H6.mat`; where can we get these?

**Comment by s-good** [comment]
> This test requires some parameter files `data/TEMP_MIN_MAX.nc`, `data/GRID_MIN_MAX.nc` and `data/info_DGG4H6.mat`; where can we get these?

They should all be downloadable from here: https://www.seanoe.org/data/00660/77199/.
