### ISSUE TITLE
Identify a body of data to analyze

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#48]
Since a usable version 1 of this project is on the horizon, it would be good to identify a body of data we'd like to analyze in early studies.

**Comment by s-good** [comment]
Hi @BillMills , we have a large test dataset that we can use (>500 MB of data) which the 150 profile test dataset was extracted from. I've had to make a few modifications to the code to allow it to run without running out memory, which is not quite ready yet.

**Comment by BillMills** [comment]
Now that #59 is merged (thanks @s-good!), as I commented in that PR it would be good to make this data available if there aren't any problems with distribution rights.
