### ISSUE TITLE
Implement WOD range check

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#50]
Code up the range test described at http://data.nodc.noaa.gov/woa/WOD/DOC/wodreadme.pdf on page 47. The program file should be called WOD_range_check.py and be put into the qctests directory. It should follow the structure shown in EN_range_check.py.

This requires reading in a data file that is used each time the quality control check is run. It would therefore be most efficient to read this in once in the main program and pass the data to the quality control check.

**Comment by BillMills** [comment]
Resources for composing this test:
 - [lat / long associated with region code](http://data.nodc.noaa.gov/woa/WOD/MASKS/range_area.msk)
 - [region code associated with region name](http://data.nodc.noaa.gov/woa/WOD/MASKS/range_basin_list.msk)
 - [region name associated with max / min temperatures by depth](http://data.nodc.noaa.gov/woa/WOD/DOC/wodreadme.pdf), appendix 9.1

Does appendix 9.1 listed above exist as a CSV somewhere?

**Comment by s-good** [comment]
Hi @BoyerWOD - is appendix 9.1 from the WOD readme doc available as a CSV file?

**Comment by BillMills** [comment]
@BoyerWOD yes please! If an official csv or json of that table is available, that would be ideal; #78 extracts it well enough for development to proceed, but the validation there is not up to production code atm.

**Comment by BoyerWOD** [comment]
Please find the following min/max range files:
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Temperature.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Salinity.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Oxygen.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Nitrate.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Phosphate.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Silicate.csv

Note that ranges have been updated in some cases from the User Manual
and new geographic areas have been added in the Northwest Pacific in conjunction with our regional atlas of the East Asian Seas.

**Comment by BoyerWOD** [comment]
I should add that we will update the one-degree geographic range distribution file and list of range areas on http://www.nodc.noaa.gov/OC5/WOD/wod_masks.html once the East Asian Seas atlas is released, probably in the next month.

**Comment by BillMills** [comment]
Brilliant! Thanks very much @BoyerWOD; will use these to replace #78.

With that, the links in the top post above should be enough to settle this issue - will have a look myself this weekend. Thanks again!

**Comment by BillMills** [comment]
hmm - on closer look, there seems to be a little glitch with the last 5 lines of `WOD_ranges_Temperature.csv`; the 5th to last doesn't have the right number of columns, and all 5 seem to repeat information for depths already reported; @BoyerWOD, I assume these lines should just be dropped?

**Comment by BoyerWOD** [comment]
Yes, last five lines are an artifact of a previous, imperfect run of the software which created the csv files.  I should have checked closer or erased files before rerunning.  I have posted corrected files to our ftp site:
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Temperature.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Salinity.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Oxygen.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Nitrate.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Phosphate.csv
ftp://ftp.nodc.noaa.gov/pub/WOD/SELECT/WOD_ranges_Silicate.csv
or you can simply ignore/remove the last five lines of each file from the previous post.

**Comment by BillMills** [comment]
OK, that's got it, looks good - thanks again @BoyerWOD.
