### ISSUE TITLE
wod decoding: missing data edge case

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#62]
When some data is missing from a profile's primary header, the corresponding key is never inserted into the primary header dictionary by `_interpret_data`.

As a result, functions like
```
    def time(self):
        """ Returns the time. """
        return self.primary_header['Time']
```

return a `KeyError` when they go looking for them; reproduce this by inserting a call to `p.time()` in any of the qc tests and running on the testing data.

We could solve this by putting exception handling into each downstream function, but I would recommend keeping the keys for every primary header dictionary always exactly the same, and assigning a value of `None` when something is missing. That way everything remains as consistent as possible - thoughts, @s-good?

**Comment by s-good** [comment]
@BillMills - please could you check if I've solved the problem satisfactorily?

**Comment by BillMills** [comment]
the new `wod_tests.py` checks behavior for calling `p.time()` and nothing goes too wrong, so I'm going to call this fixed. Thanks @s-good !
