### ISSUE TITLE
kristenvogt: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by kristenvogt** [IQuOD/AutoQC#70]
It sounds neat! <p><br><blockquote>This issue was created by @kristenvogt via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by s-good** [comment]
Hi @kristenvogt  - thanks! It is shaping up to be a really useful resource for processing ocean data but we need to get as many quality control checks coded up as possible. We'd love to get your help.

**Comment by kristenvogt** [comment]
Hi Simon!

Just as a heads-up, I'm very new at this; I kind of have no idea what I'm
doing.

On Thu, Jun 4, 2015 at 9:37 AM, Simon Good <notifications@github.com> wrote:

> Hi @kristenvogt <https://github.com/kristenvogt> - thanks! It is shaping
> up to be a really useful resource for processing ocean data but we need to
> get as many quality control checks coded up as possible. We'd love to get
> your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IQuOD/AutoQC/issues/70#issuecomment-108917599>.
>



-- 
Kristen Vogt Veggeberg
Doctoral Student and Researcher
Department of Curriculum & Instruction
3252 EPASW
1040 W. Harrison M/C 147
Chicago, IL 60607
773-370-4106

**Comment by s-good** [comment]
No worries! The best thing is to take a look at some of the examples in the qctests directory e.g. WOD_gradient_check.py, then base a new quality control check on that. #64 might be a good one to start work on. 

The description of the test may sound a bit difficult to understand, but the main thing is calculating density at each point in the profile (which is a series of observations made down through the ocean) by first using the pottem function in util/obs_utils.py to calculate potential temperature (see example in EN_background_check.py) and then the density function, also in util/obs_utils.py. Then you can work through the logic to work out which data points should get rejected by the test.

**Comment by BillMills** [comment]
@kristenvogt how are things going? Delighted to have you on board, let us know if you have any questions or if we can help at all! Happy to chat if I can do anything at all.
