### ISSUE TITLE
Standalone wod.py

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#94]
It occurs to me that we could do a service to the ocean science community with very little extra work, by splitting `wod.py` and related docs + tests out into their own package and listing it on PyPI - that way, anyone who wants to read WOD files would have a tool to do so.

I'm happy to take care of the details personally - as long as there are no objections from @s-good ?

**Comment by s-good** [comment]
Hi @BillMills, good idea. @BoyerWOD, what do you think?

**Comment by BoyerWOD** [comment]
Yes, I agree, that is a good idea.

**Comment by BillMills** [comment]
Alright, a first cut of this exists on PyPI; installation: `sudo pip install wodpy`

Check out the [source repo](https://github.com/BillMills/wodpy) and a [toy example](https://github.com/BillMills/woddemo). The toy example's README has some instructions for checking if things install and run smoothly on your machines; things work fine on OSX, but I'm a bit dubious of what's going to happen on a windows machine, and would like to confirm things work there before we migrate AutoQC to using this package.

**Comment by BillMills** [comment]
As mentioned in https://github.com/IQuOD/wodpy/issues/1, I'm ready to call wodpy done at 1.0 - if there are no objections, I'll wrap it up and ship it, and then we can migrate AutoQC to use this module and close this issue.

**Comment by BillMills** [comment]
Thanks everyone for your comments - `wodpy` is now available at 1.0 on PyPI

`sudo pip install wodpy`

Please cite this version via the DOI 10.5281/zenodo.31213.
