### ISSUE TITLE
Goals for Hamburg

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#95]
Hi @s-good @BecCowley et al - while we've still got some time, it would be good to set a goal for results to present in Hamburg. Finishing the outstanding tests (#54, #56 & #64) would be a good start, but also having something to present in terms of decision-making performance would be a great thing to be able to report. A machine learning strategy is described in #60, which I'm interested to execute on, but as I mention in #48, we need a larger dataset to train and test on (several thousand profiles). 

Let me know what you'd like to show in Hamburg, and we'll try to make it happen.

**Comment by s-good** [comment]
Hi @BillMills , thanks for your message. I had a thought about the decision-making performance and implemented a simple algorithm that generates a subset of the full range of possibilities (#96). It runs quick but obviously is not so comprehensive. The machine learning strategy would still be interesting as there may be better combinations that the simple method does not find. I also put in a test for the EN background check.

I think that the first priorities for the Hamburg meeting is to get as many tests as possible finished and get some interesting results to show. I hope that we can really inspire the people there to contribute.

I will find the location of the larger dataset and send you in an email. We are concerned there may be some errors in it so don't want to distribute publicly yet.
